---
abstract: 'Modules SCHWIGON uses'
author:
  - 'Steffen Schwigon <ss5@renormalist.net>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-SCHWIGON
requires:
  App::Ack: 0
  App::Cmd: 0
  App::DPath: 0
  App::Nopaste: 0
  App::Rad: 0
  App::Software::License: 0
  App::cpanminus: 0
  App::cpanoutdated: 0
  Archive::Tar::Wrapper: 0
  Bundle::CPANxxl: 0
  Bundle::LWP: 0
  Bundle::libnet: 0
  CPAN::Mini: 0
  CPAN::Mini::Devel: 0
  CPAN::Reporter: 0
  CPAN::Uploader: 0
  Cache::Cache: 0
  Cache::FileCache: 0
  DBD::Pg: 0
  DBD::SQLite: 0
  DBD::mysql: 0
  DBI: 0
  DBIx::Class: 0
  DBIx::Class::Schema::Loader: 0
  DBIx::Class::Schema::Versioned: 0
  DBIx::Class::TimeStamp: 0
  Data::DPath: 0
  Data::Visitor: 0
  Data::YAML: 0
  DateTime: 0
  DateTime::Format::Builder: 0
  DateTime::Format::Mail: 0
  DateTime::Format::MySQL: 0
  DateTime::Format::Natural: 0
  DateTime::Format::Strptime: 0
  Devel::Backtrace: 0
  Devel::Cover: 0
  Devel::NYTProf: 0
  Devel::bt: 0
  Digest::SHA1: 0
  Directory::Scratch: 0
  Dist::Zilla: 0
  Dist::Zilla::PluginBundle::SCHWIGON: 0
  Dist::Zilla::PluginBundle::TAPPER: 0
  File::ShareDir: 0
  File::Slurp: 0
  File::Type: 0
  Hash::Merge: 0
  Hash::Merge::Simple: 0
  JSON: 0
  JSON::Syck: 0
  JSON::XS: 0
  List::AllUtils: 0
  List::MoreUtils: 0
  Log::Log4perl: 0
  Module::Install: 0.95
  Module::Install::AuthorRequires: 0
  Module::Install::AuthorTests: 0
  Module::Install::CheckConflicts: 0
  Module::Install::ExtraTests: 0
  Moose: 0
  Moose::Autobox: 0
  MooseX::Daemonize: 0
  MooseX::Declare: 0
  MooseX::LazyRequire: 0
  MooseX::Log::Log4perl: 0
  MooseX::Method::Signatures: 0
  MooseX::Types::Common: 0
  MooseX::Types::DateTime: 0
  MooseX::Types::Email: 0
  MooseX::Types::LoadableClass: 0
  MooseX::Types::Path::Class: 0
  MooseX::Types::URI: 0
  Net::Daemon: 0
  Net::SSH: 0
  Net::SSH::Expect: 0
  Net::Server: 0
  Net::Server::PreForkSimple: 0
  Net::TFTP: 0
  PadWalker: 0
  Parse::RecDescent: 0
  Perl::Tidy: 0
  Perl::Version: 1.010
  Pod::Coverage::TrustPod: 0
  Pod::Weaver::PluginBundle::SCHWIGON: 0
  Pod::Weaver::PluginBundle::TAPPER: 0
  Regexp::Common: 0
  SQL::Translator: 0
  Sub::Exporter: 0
  TAP::DOM: 0
  TAP::Formatter::HTML: 0
  TAP::Parser::Aggregator: 0
  Task::PerlFormance: 0
  Task::SDK::Moose: 0
  Template: 0
  Term::ReadLine::Gnu: 0
  Term::ReadLine::Perl: 0
  Test::Aggregate: 0
  Test::Deep: 0
  Test::Fixture::DBIC::Schema: 0
  Test::MockModule: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Reporter: 0
  Test::Reporter::Transport::Socket: 0
  Test::WWW::Mechanize::Catalyst: 0
  TryCatch: 0
  URI: 0
  URI::Escape: 0
  V: 0
  YAML: 0
  YAML::Syck: 0
  YAML::XS: 0
  bareword::filehandles: 0
  indirect: 0
  multidimensional: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Task-BeLike-SCHWIGON
  homepage: http://metacpan.org/release/Task-BeLike-SCHWIGON
  repository: git://github.com/renormalist/Task-BeLike-SCHWIGON.git
version: 0.003
x_Dist_Zilla:
  perl:
    version: 5.016003
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@SCHWIGON/@Basic/GatherDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@SCHWIGON/@Basic/PruneCruft'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@SCHWIGON/@Basic/ManifestSkip'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@SCHWIGON/@Basic/MetaYAML'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::License
      name: '@SCHWIGON/@Basic/License'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@SCHWIGON/@Basic/Readme'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@SCHWIGON/@Basic/ExtraTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@SCHWIGON/@Basic/ExecDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@SCHWIGON/@Basic/ShareDir'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@SCHWIGON/@Basic/MakeMaker'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@SCHWIGON/@Basic/Manifest'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@SCHWIGON/@Basic/TestRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@SCHWIGON/@Basic/ConfirmRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@SCHWIGON/@Basic/UploadToCPAN'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@SCHWIGON/MetaConfig'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@SCHWIGON/MetaJSON'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@SCHWIGON/PkgVersion'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@SCHWIGON/PodSyntaxTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@SCHWIGON/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@SCHWIGON/PodCoverageTests'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@SCHWIGON/MetaResources'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@SCHWIGON/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@SCHWIGON/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::TaskWeaver
      name: '@SCHWIGON/TaskWeaver'
      version: 0.101624
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@SCHWIGON/AutoPrereqs'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@SCHWIGON/Git::Describe'
      version: 0.002
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@SCHWIGON/CheckChangesHasContent'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@SCHWIGON/NextRelease'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@SCHWIGON/Git::CheckFor::CorrectBranch'
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@SCHWIGON/Git::NextVersion'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@SCHWIGON/@Git/Check'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@SCHWIGON/@Git/Commit'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@SCHWIGON/@Git/Tag'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@SCHWIGON/@Git/Push'
      version: 2.013
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300034
x_authority: cpan:SCHWIGON
